name: intellibra
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+3
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  auto_route: ^5.0.4
  bloc: ^8.1.1
  cloud_firestore: ^4.4.3
  collection: ^1.17.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_blue_plus: ^1.10.9
  flutter_hicons: ^0.1.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.18
  get_it: ^7.2.0
  google_fonts: ^5.1.0
  hydrated_bloc: ^9.1.0
  iconly: ^1.0.1
  intl: ^0.18.0
  palette_generator: ^0.3.3+2
  path_provider: ^2.0.13
  permission_handler: ^10.4.3
  pinput: ^2.2.31
  url_launcher: ^6.1.10

dev_dependencies:
  auto_route_generator: ^5.0.3
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  fast_i18n: ^5.12.6
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/icons/
icons_launcher:
  image_path: "assets/icons/app-icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
flutter_assets:
  assets_path: assets/
  output_path: lib/src/app/
  filename: assets.dart
