// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWGo35-3ufP8xs65FY31dXx_h0bGxfIag',
    appId: '1:602426551207:web:9a3e30074355d91cfc6482',
    messagingSenderId: '602426551207',
    projectId: 'intellibra-ecb00',
    authDomain: 'intellibra-ecb00.firebaseapp.com',
    storageBucket: 'intellibra-ecb00.appspot.com',
    measurementId: 'G-6CF7F7HWC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbvj4BpjWr_i1LCG8GbEJksnje1PQf7yA',
    appId: '1:602426551207:android:360824a3dc9771befc6482',
    messagingSenderId: '602426551207',
    projectId: 'intellibra-ecb00',
    storageBucket: 'intellibra-ecb00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbDiY37f54GsHu4ps4szNJDam5YU0RUf0',
    appId: '1:602426551207:ios:532aa0a5cbd4d009fc6482',
    messagingSenderId: '602426551207',
    projectId: 'intellibra-ecb00',
    storageBucket: 'intellibra-ecb00.appspot.com',
    androidClientId: '602426551207-c7rbmmquurjcihukqtu3pv707nrh2as3.apps.googleusercontent.com',
    iosClientId: '602426551207-4t4a6vc6erdcnb5npvqubu1ejkhlsm8q.apps.googleusercontent.com',
    iosBundleId: 'org.xenora.intellibra.intellibra',
  );
}
