// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNu3spMVVUiTDjYgl05g2bd8f9Sy6Ro-Y',
    appId: '1:317604373926:web:d6a17791d20cfb52249b67',
    messagingSenderId: '317604373926',
    projectId: 'intellibra-mobile',
    authDomain: 'intellibra-mobile.firebaseapp.com',
    storageBucket: 'intellibra-mobile.appspot.com',
    measurementId: 'G-QPCRQ139GX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_MZLvIXQSCOA8Z8qNXbO31M3_x5Ov-Mw',
    appId: '1:317604373926:android:53d924dafac36933249b67',
    messagingSenderId: '317604373926',
    projectId: 'intellibra-mobile',
    storageBucket: 'intellibra-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD6otPgCMRuKCDMTrx2DjBMSSxLllKYq4',
    appId: '1:317604373926:ios:c5bae7ed2e9c6ce7249b67',
    messagingSenderId: '317604373926',
    projectId: 'intellibra-mobile',
    storageBucket: 'intellibra-mobile.appspot.com',
    iosBundleId: 'org.xenora.intellibra.intellibra',
  );
}
